spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 101645994504-mbtnmshmg7u3sd9klpg79hhammp83iqt.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
